swagger: "2.0"
info:
  version: "0.0.1"
  title: Storage Happy API
# during dev, should point to your local machine
host: localhost:31337
# basePath prefixes all resource paths 
basePath: /api
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /v1/store/{name}/{path}:
    # binds a127 app logic to a route
    x-swagger-router-controller: storage
    delete:
      description: Deletes file at path and returns stream upload url
      operationId: delete
      parameters:
        - name: name
          in: path
          description: store name
          required: true
          type: string
        - name: path
          in: path
          description: lists items at storage path
          required: true
          type: string
        - name: Authorization
          in: header
          description: authorization bearer token
          required: false
          type: string
        - name: X-AppId
          in: header
          description: application identification
          required: true
          type: string        
        - name: file
          in: body
          description: file description
          required: true
          schema:
            $ref: "#/definitions/File"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DataUploadResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "403":
          description: Forbidden
          schema:
            $ref: "#/definitions/ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Updates file at path and returns stream upload url
      operationId: update
      parameters:
        - name: name
          in: path
          description: store name
          required: true
          type: string
        - name: path
          in: path
          description: lists items at storage path
          required: true
          type: string
        - name: Authorization
          in: header
          description: authorization bearer token
          required: false
          type: string
        - name: X-AppId
          in: header
          description: application identification
          required: true
          type: string        
        - name: file
          in: body
          description: file description
          required: true
          schema:
            $ref: "#/definitions/File"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DataUploadResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "403":
          description: Forbidden
          schema:
            $ref: "#/definitions/ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Creates file at path and returns stream upload url
      operationId: create
      parameters:
        - name: name
          in: path
          description: store name
          required: true
          type: string
        - name: path
          in: path
          description: lists items at storage path
          required: true
          type: string
        - name: Authorization
          in: header
          description: authorization bearer token
          required: false
          type: string
        - name: X-AppId
          in: header
          description: application identification
          required: true
          type: string        
        - name: file
          in: body
          description: file description
          required: true
          schema:
            $ref: "#/definitions/File"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DataUploadResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "403":
          description: Forbidden
          schema:
            $ref: "#/definitions/ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      description: Lists files and folders at path
      # used as the method name of the controller
      operationId: list
      parameters:
        - name: name
          in: path
          description: store name
          required: true
          type: string
        - name: path
          in: path
          description: lists items at storage path
          required: true
          type: string
        - name: filter
          in: query
          description: query path filter
          required: false
          type: string
        - name: Authorization
          in: header
          description: authorization bearer token
          required: false
          type: string
        - name: X-AppId
          in: header
          description: application identification
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/FileListResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "403":
          description: Forbidden
          schema:
            $ref: "#/definitions/ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        "409":
          description: Conflict
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  DataUploadResponse:
    description: File upload stream descriptor
    properties:
      link:
        type: string
  FileListResponse:
    description: Files list object.
    properties:
      files:
        type: array
        items:
          $ref: "#/definitions/File"
  File:
    description: File descriptor
    properties:
      name:
        type: string
      tag:
        type: string
      modifiedDate:
        type: number
      type:
        type: string
        enum:
          - file
          - folder
      mime:
        type: string
      link:
        type: string
    required:
      - name
      - tag
      - mime
      - type
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
